import os
import sys
import platform

Import("env")

env.Append(LIBS = ['network', 'bnetapi'])

BNetworkAddress = env.Clone()
BNetworkAddress.Program(target = 'BNetworkAddress',
	source = ['#external/tpunitpp/libtpunit++main.a', 'BNetworkAddress.cpp'])

BNetworkAddressResolver = env.Clone()
BNetworkAddressResolver.Program(target = 'BNetworkAddressResolver',
	source = ['#external/tpunitpp/libtpunit++main.a', 'BNetworkAddressResolver.cpp'])
