import os
import sys
import platform

Import("env")

env.Append(LIBS = ['network', 'bnetapi'])

framework_code = ['#/external/tpunitpp/tpunit++main.cpp']

bnetworkaddress_code = framework_code + ['BNetworkAddress.cpp']

BNetworkAddress = env.Clone()
BNetworkAddress.Program(target = 'BNetworkAddress', source = bnetworkaddress_code)
